import type { DataCollection } from '@wix/astro/builders'

export const collectionIdSuffix = 'faq-items';

export default {
  idSuffix: collectionIdSuffix,
  displayName: 'FAQ Items',
  fields: [
    {
      type: 'TEXT',
      displayName: 'Group ID',
      key: 'groupId',
    },
    {
      type: 'TEXT',
      displayName: 'Question',
      key: 'question',
    },
    {
      type: 'RICH_TEXT',
      displayName: 'Answer',
      key: 'answer',
    },
    { type: 'TEXT', displayName: 'Category', key: 'category' },
    { type: 'NUMBER', displayName: 'Sort Order', key: 'sortOrder' },
    { type: 'BOOLEAN', displayName: 'Published', key: 'published' },
    { type: 'TEXT', displayName: 'Title', key: 'title' },
  ],
  displayField: 'title',
  dataPermissions: {
    itemInsert: 'CMS_EDITOR',
    itemRead: 'ANYONE',
    itemRemove: 'CMS_EDITOR',
    itemUpdate: 'CMS_EDITOR',
  },
  indexes: [],
  initialData: [
    {
      _id: 'starter-faq-item-1',
      title: 'How do I connect my FAQ widget?',
      groupId: 'starter-faq-group',
      question: 'How do I connect my FAQ widget?',
      answer: '<p>Open the widget settings in the Wix Editor and choose <strong>Getting Started</strong> from the FAQ connection key dropdown.</p>',
      category: 'Getting Started',
      sortOrder: 0,
      published: true,
    },
    {
      _id: 'starter-faq-item-2',
      title: 'Can I customize the appearance?',
      groupId: 'starter-faq-group',
      question: 'Can I customize the appearance?',
      answer: '<p>Yes. Choose a layout preset, then adjust colors, typography, icons, padding, and margins in the widget settings panel.</p>',
      category: 'Customization',
      sortOrder: 1,
      published: true,
    },
    {
      _id: 'starter-faq-item-3',
      title: 'How do I add more questions?',
      groupId: 'starter-faq-group',
      question: 'How do I add more questions?',
      answer: '<p>Use the dashboard to select the group, write a question and rich-text answer, and click <strong>Add FAQ</strong>.</p>',
      category: 'Content',
      sortOrder: 2,
      published: true,
    },
    {
      _id: 'starter-faq-item-4',
      title: 'Can I use images and videos in answers?',
      groupId: 'starter-faq-group',
      question: 'Can I use images and videos in answers?',
      answer: '<p>Yes. The dashboard answer editor supports rich text, links, images, and video embeds.</p>',
      category: 'Content',
      sortOrder: 3,
      published: true,
    },
    {
      _id: 'starter-faq-item-5',
      title: 'Can I change the spacing around the widget?',
      groupId: 'starter-faq-group',
      question: 'Can I change the spacing around the widget?',
      answer: '<p>Yes. Open the <strong>Container</strong> section and set the padding and each margin independently.</p>',
      category: 'Customization',
      sortOrder: 4,
      published: true,
    },
    {
      _id: 'starter-faq-item-6',
      title: 'Can I change the accordion icon?',
      groupId: 'starter-faq-group',
      question: 'Can I change the accordion icon?',
      answer: '<p>Yes. Choose a preset with a different icon, or select the icon style in the <strong>Icon &amp; behavior</strong> section.</p>',
      category: 'Customization',
      sortOrder: 5,
      published: true,
    },
    {
      _id: 'starter-faq-item-7',
      title: 'Can I publish or hide a group?',
      groupId: 'starter-faq-group',
      question: 'Can I publish or hide a group?',
      answer: '<p>Yes. Use the publish action on the FAQ group card. Only published groups and FAQ items appear on your live site.</p>',
      category: 'Publishing',
      sortOrder: 6,
      published: true,
    },
    {
      _id: 'starter-faq-item-8',
      title: 'Will the FAQ work on mobile devices?',
      groupId: 'starter-faq-group',
      question: 'Will the FAQ work on mobile devices?',
      answer: '<p>Yes. The widget is responsive and adapts its layout, spacing, and text to smaller screens.</p>',
      category: 'Getting Started',
      sortOrder: 7,
      published: true,
    },
  ],
} satisfies DataCollection;
